import Config

# Note: You should never commit sensitive data to version control.
# Instead, use environment variables or a secure secret management system.

# Configure your database
config :beam_slides, BeamSlidesWeb.Endpoint,
  url: [host: "localhost", port: 4000],
  http: [
    port: String.to_integer(System.get_env("PORT") || "4000"),
    transport_options: [socket_opts: [:inet6]]
  ],
  secret_key_base: "dummy_key_for_slides_only",
  server: true,
  check_origin: false,
  code_reloader: false,
  debug_errors: false,
  static_url: "/"

# Do not print debug messages in production
config :logger, level: :info

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :beam_slides, BeamSlidesWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: BeamSlides.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
